# Generated by Django 4.2.3 on 2023-07-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel_manage', '0021_alter_bookingdetails_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookings', models.IntegerField()),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('pending_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel_manage.hoteldetails')),
            ],
        ),
    ]
