# Generated by Django 4.2.3 on 2023-07-10 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('hotel_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_email', models.EmailField(max_length=254)),
                ('hotel_registration_number', models.CharField(max_length=255)),
                ('hotel_contact_number', models.CharField(max_length=20)),
                ('hotel_address', models.CharField(max_length=255)),
                ('hotel_location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=10)),
                ('hotel_owner_name', models.CharField(max_length=255)),
                ('hotel_owner_email', models.EmailField(max_length=254)),
                ('hotel_owner_contact', models.CharField(max_length=20)),
                ('hotel_owner_address', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
