# Generated by Django 4.2.3 on 2023-07-17 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_email', models.EmailField(max_length=254)),
                ('hotel_registration_number', models.CharField(max_length=255)),
                ('hotel_contact_number', models.CharField(max_length=20)),
                ('hotel_address', models.CharField(max_length=255)),
                ('hotel_location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=10)),
                ('hotel_profile', models.ImageField(upload_to='hotel_profile/')),
                ('hotel_owner_name', models.CharField(max_length=255)),
                ('hotel_owner_email', models.EmailField(max_length=254)),
                ('hotel_owner_contact', models.CharField(max_length=20)),
                ('hotel_owner_address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
