# Generated by Django 4.2.3 on 2023-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='is_logined',
            field=models.BooleanField(default=False),
        ),
    ]
