# Generated by Django 4.2.3 on 2023-07-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='hotel_profile',
            field=models.ImageField(default=1, upload_to='hotel_profile/'),
            preserve_default=False,
        ),
    ]
