# Generated by Django 4.2.3 on 2023-07-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0004_roomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='hotel',
            new_name='hotel_id',
        ),
    ]
