# Generated by Django 4.2.3 on 2023-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0006_bookingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='id_card',
            field=models.ImageField(default=1, upload_to='roomuser_idcard/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='special_requests',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
