# Generated by Django 4.2.3 on 2023-07-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0008_bookingdetails_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetails',
            name='hotel_owner_address',
        ),
        migrations.RemoveField(
            model_name='hoteldetails',
            name='hotel_owner_contact',
        ),
        migrations.RemoveField(
            model_name='hoteldetails',
            name='hotel_owner_email',
        ),
        migrations.RemoveField(
            model_name='hoteldetails',
            name='hotel_owner_name',
        ),
        migrations.CreateModel(
            name='Hotelowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_contact', models.CharField(max_length=20)),
                ('owner_address', models.CharField(max_length=255)),
                ('id_card', models.ImageField(upload_to='hotelowner_idcard/')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_manage.hoteldetails')),
            ],
        ),
    ]
