# Generated by Django 4.2.3 on 2023-07-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0009_remove_hoteldetails_hotel_owner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='is_registerd',
            field=models.BooleanField(default=False),
        ),
    ]
