# Generated by Django 4.2.3 on 2023-07-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='is_account_add',
            field=models.BooleanField(default=False),
        ),
    ]
