# Generated by Django 4.2.3 on 2023-07-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0013_bookingdetails_room_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='room_count',
        ),
    ]
