# Generated by Django 4.2.3 on 2023-07-22 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotel_manage', '0016_rename_payment_date_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentDetails',
        ),
    ]
