# Generated by Django 4.2.3 on 2023-07-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0017_rename_payment_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='is_advancepaid',
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='razor_pay_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
