# Generated by Django 4.2.3 on 2023-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0018_remove_bookingdetails_is_advancepaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='razor_pay_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
