# Generated by Django 4.2.3 on 2023-07-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0019_alter_paymentdetails_razor_pay_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldetails',
            old_name='is_account_add',
            new_name='is_confirmed',
        ),
    ]
