# Generated by Django 4.2.3 on 2023-07-27 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0021_alter_bookingdetails_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hotel_manage.bookingdetails'),
            preserve_default=False,
        ),
    ]
