# Generated by Django 4.2.3 on 2023-07-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0022_paymentdetails_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='room_count',
        ),
    ]
