# Generated by Django 4.2.3 on 2023-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0023_remove_bookingdetails_room_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
