# Generated by Django 4.2.3 on 2023-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0024_roomtype_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
    ]
