# Generated by Django 4.2.3 on 2023-07-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0025_roomtype_check_out_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='is_reserved',
        ),
    ]
