# Generated by Django 4.2.3 on 2023-07-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='mail_activation',
        ),
    ]
