# Generated by Django 4.2.3 on 2023-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_manage', '0002_remove_userdetails_mail_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
