# Generated by Django 4.2.3 on 2023-07-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_manage', '0005_alter_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='mail_activation',
            field=models.BooleanField(default=False),
        ),
    ]
