# Generated by Django 4.2.3 on 2023-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_manage', '0006_userdetails_mail_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mail_activation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
